Whitelist:
- playertowhitelist
- playertowhitelist2
Config:
  Notify: true
  ShowLog: false
  Msg:
    NotWhitelisted: "You are not whitelisted!"
    Notified: "Your not whitelisted. An admin may add you. Try again in 20secs"
    NoAdminOnline: "Your not whitelisted and there is no admin online"
    TryLater: "You just tried to join... try again in 20secs"
