name: Whitelisted
version: 1.0.4
description: This plugin lets you whitelist players via file or commands
author: Kantenkugel

main: me.kantenkugel.serveress.whitelisted.Whitelisted

commands:
    whitelisted:
        description: Prints the help with subcommands.
        usage: |
            Usage:
            /<command> - Prints the help.
            /<command> add PLAYER - Adds a Player to the Whitelist
            /<command> rem PLAYER - Removes a Player from the Whitelist
            /<command> deny PLAYER - Denies the Player so no Notice is printed again.
            /<command> list - Lists all the Players that are Whitelisted
            /<command> reload - reload the Config
        aliases: wl
    

permissions:
    whitelisted.*:
        description: allows access to all of whitelisteds functions
        children:
            whitelisted.admin: true
            whitelisted.join: true
    whitelisted.admin:
        description: grants you access to the ingame-commands
        default: op
    whitelisted.join:
        description: lets you join even if your not in the whitelist-file
        default: op
